/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FontFamily: typeof import('./src/components/book_dialog_list/fontFamily/index.vue')['default']
    FontSize: typeof import('./src/components/book_dialog_list/fontSize/index.vue')['default']
    Progress: typeof import('./src/components/book_dialog_list/progress/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import("./src/components/book_dialog_list/themeColor/index.vue")["default"]
    ThemeColor: typeof import('./src/components/book_dialog_list/themeColor/index.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSlider: typeof import('vant/es')['Slider']
  }
}
