/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Book_detail: typeof import('./src/components/book_detail/index.vue')['default']
    Brief_info: typeof import('./src/components/menuBar_directory_cpms/directory_detailed/detailed_cpms/brief_info/index.vue')['default']
    Directory: typeof import('./src/components/book_dialog_list/directory/index.vue')['default']
    Directory_bookmark: typeof import('./src/components/menuBar_directory_cpms/directory_bookmark/index.vue')['default']
    Directory_content: typeof import('./src/components/menuBar_directory_cpms/directory_content/index.vue')['default']
    Directory_detailed: typeof import('./src/components/menuBar_directory_cpms/directory_detailed/index.vue')['default']
    Directory_search: typeof import('./src/components/menuBar_directory_cpms/directory_search/index.vue')['default']
    Fold_directory: typeof import('./src/components/menuBar_directory_cpms/directory_detailed/detailed_cpms/fold_directory/index.vue')['default']
    Fold_recursion: typeof import('./src/components/menuBar_directory_cpms/directory_detailed/detailed_cpms/fold_directory/fold_recursion.vue')['default']
    FontFamily: typeof import('./src/components/book_dialog_list/fontFamily/index.vue')['default']
    FontSize: typeof import('./src/components/book_dialog_list/fontSize/index.vue')['default']
    Home_classification: typeof import('./src/components/home_classification/index.vue')['default']
    Progress: typeof import('./src/components/book_dialog_list/progress/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeColor: typeof import('./src/components/book_dialog_list/themeColor/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanUploader: typeof import('vant/es')['Uploader']
    VanWatermark: typeof import('vant/es')['Watermark']
  }
}
